<?php

/**
 * This file is part of the NameDayControl package
 *
 * Copyright (c) 2013 Petr Kessler (http://kesspess.1991.cz)
 *
 * @license  MIT
 * @link     https://github.com/uestla/NameDayControl
 */

namespace Components\Controls;

use Nette;


class NameDayControl extends BaseControl
{

	/** @var array pole svatku - struktura array( MESIC => array( DEN => array('Jmenovec', (bool) IS_SPECIAL_DAY, (int) count ), ... ), ... ) */
	protected static $namedays = array(
		1 => array(
			1 => array('Nový rok', TRUE, 1),
			array('Karina', FALSE, 1),
			array('Radmila', FALSE, 1),
			array('Diana', FALSE, 1),
			array('Dalimil', FALSE, 1),
			array('svátek Tří králů', TRUE, 3),
			array('Vilma', FALSE, 1),
			array('Čestmír', FALSE, 1),
			array('Vladan', FALSE, 1),
			array('Břetislav', FALSE, 1),
			array('Bohdana', FALSE, 1),
			array('Pravoslav', FALSE, 1),
			array('Edita', FALSE, 1),
			array('Radovan', FALSE, 1),
			array('Alice', FALSE, 1),
			array('Ctirad', FALSE, 1),
			array('Drahoslav', FALSE, 1),
			array('Vladislav', FALSE, 1),
			array('Doubravka', FALSE, 1),
			array('Ilona', FALSE, 1),
			array('Běla', FALSE, 1),
			array('Slavomír', FALSE, 1),
			array('Zdeněk', FALSE, 1),
			array('Milena', FALSE, 1),
			array('Miloš', FALSE, 1),
			array('Zora', FALSE, 1),
			array('Ingrid', FALSE, 1),
			array('Otýlie', FALSE, 1),
			array('Zdislava', FALSE, 1),
			array('Robin', FALSE, 1),
			array('Marika', FALSE, 1),
		),

		2 => array(
			1 => array('Hynek', FALSE, 1),
			array('Nela', FALSE, 1),
			array('Blažej', FALSE, 1),
			array('Jarmila', FALSE, 1),
			array('Dobromila', FALSE, 1),
			array('Vanda', FALSE, 1),
			array('Veronika', FALSE, 1),
			array('Milada', FALSE, 1),
			array('Apolena', FALSE, 1),
			array('Mojmír', FALSE, 1),
			array('Božena', FALSE, 1),
			array('Slavěna', FALSE, 1),
			array('Věnceslav', FALSE, 1),
			array('Valentýn', FALSE, 1),
			array('Jiřina', FALSE, 1),
			array('Ljuba', FALSE, 1),
			array('Miloslava', FALSE, 1),
			array('Gizela', FALSE, 1),
			array('Patrik', FALSE, 1),
			array('Oldřich', FALSE, 1),
			array('Lenka', FALSE, 1),
			array('Petr', FALSE, 1),
			array('Svatopluk', FALSE, 1),
			array('Matěj', FALSE, 1),
			array('Liliana', FALSE, 1),
			array('Dorota', FALSE, 1),
			array('Alexandr', FALSE, 1),
			array('Lumír', FALSE, 1),
			array('Horymír', FALSE, 1),
		),

		3 => array(
			1 => array('Bedřich', FALSE, 1),
			array('Anežka', FALSE, 1),
			array('Kamil', FALSE, 1),
			array('Stela', FALSE, 1),
			array('Kazimir', FALSE, 1),
			array('Miroslav', FALSE, 1),
			array('Tomáš', FALSE, 1),
			array('Gabriela', FALSE, 1),
			array('Františka', FALSE, 1),
			array('Viktorie', FALSE, 1),
			array('Anděla', FALSE, 1),
			array('Řehoř', FALSE, 1),
			array('Růžena', FALSE, 1),
			array('Rút a Matylda', FALSE, 2),
			array('Ida', FALSE, 1),
			array('Elena a Herbert', FALSE, 2),
			array('Vlastimil', FALSE, 1),
			array('Eduard', FALSE, 1),
			array('Josef', FALSE, 1),
			array('Světlana', FALSE, 1),
			array('Radek', FALSE, 1),
			array('Leona', FALSE, 1),
			array('Ivona', FALSE, 1),
			array('Gabriel', FALSE, 1),
			array('Marian', FALSE, 1),
			array('Emanuel', FALSE, 1),
			array('Dita', FALSE, 1),
			array('Soňa', FALSE, 1),
			array('Taťána', FALSE, 1),
			array('Arnošt', FALSE, 1),
			array('Kvido', FALSE, 1),
		),

		4 => array(
			1 => array('Hugo', FALSE, 1),
			array('Erika', FALSE, 1),
			array('Richard', FALSE, 1),
			array('Ivana', FALSE, 1),
			array('Miroslava', FALSE, 1),
			array('Vendula', FALSE, 1),
			array('Heřman a Hermína', FALSE, 2),
			array('Ema', FALSE, 1),
			array('Dušan', FALSE, 1),
			array('Darja', FALSE, 1),
			array('Izabela', FALSE, 1),
			array('Julius', FALSE, 1),
			array('Aleš', FALSE, 1),
			array('Vincenc', FALSE, 1),
			array('Anastázie', FALSE, 1),
			array('Irena', FALSE, 1),
			array('Rudolf', FALSE, 1),
			array('Valérie', FALSE, 1),
			array('Rostislav', FALSE, 1),
			array('Marcela', FALSE, 1),
			array('Alexandra', FALSE, 1),
			array('Evženie', FALSE, 1),
			array('Vojtěch', FALSE, 1),
			array('Jiří', FALSE, 1),
			array('Marek', FALSE, 1),
			array('Oto', FALSE, 1),
			array('Jaroslav', FALSE, 1),
			array('Vlastislav', FALSE, 1),
			array('Robert', FALSE, 1),
			array('Blahoslav', FALSE, 1),
		),

		5 => array(
			1 => array('Svátek práce', TRUE, 1),
			array('Zikmund', FALSE, 1),
			array('Alexej', FALSE, 1),
			array('Květoslav', FALSE, 1),
			array('Klaudie', FALSE, 1),
			array('Radoslav', FALSE, 1),
			array('Stanislav', FALSE, 1),
			array('Den osvobození', TRUE, 1),
			array('Ctibor', FALSE, 1),
			array('Blažena', FALSE, 1),
			array('Svatava', FALSE, 1),
			array('Pankrác', FALSE, 1),
			array('Servác', FALSE, 1),
			array('Bonifác', FALSE, 1),
			array('Žofie', FALSE, 1),
			array('Přemysl', FALSE, 1),
			array('Aneta', FALSE, 1),
			array('Nataša', FALSE, 1),
			array('Ivo', FALSE, 1),
			array('Zbyšek', FALSE, 1),
			array('Monika', FALSE, 1),
			array('Emil', FALSE, 1),
			array('Vladimír', FALSE, 1),
			array('Jana', FALSE, 1),
			array('Viola', FALSE, 1),
			array('Filip', FALSE, 1),
			array('Valdemar', FALSE, 1),
			array('Vilém', FALSE, 1),
			array('Maxmilián', FALSE, 1),
			array('Ferdinand', FALSE, 1),
			array('Kamila', FALSE, 1),
		),

		6 => array(
			1 => array('Laura', FALSE, 1),
			array('Jarmil', FALSE, 1),
			array('Tamara', FALSE, 1),
			array('Dalibor', FALSE, 1),
			array('Dobroslav', FALSE, 1),
			array('Norbert', FALSE, 1),
			array('Iveta a Slavoj', FALSE, 2),
			array('Medard', FALSE, 1),
			array('Stanislava', FALSE, 1),
			array('Gita', FALSE, 1),
			array('Bruno', FALSE, 1),
			array('Antonie', FALSE, 1),
			array('Antonín', FALSE, 1),
			array('Roland', FALSE, 1),
			array('Vít', FALSE, 1),
			array('Zbyněk', FALSE, 1),
			array('Adolf', FALSE, 1),
			array('Milan', FALSE, 1),
			array('Leoš', FALSE, 1),
			array('Květa', FALSE, 1),
			array('Alois', FALSE, 1),
			array('Pavla', FALSE, 1),
			array('Zdeňka', FALSE, 1),
			array('Jan', FALSE, 1),
			array('Ivan', FALSE, 1),
			array('Adriana', FALSE, 1),
			array('Ladislav', FALSE, 1),
			array('Lubomír', FALSE, 1),
			array('Petr a Pavel', FALSE, 2),
			array('Šárka', FALSE, 1),
		),

		7 => array(
			1 => array('Jaroslava', FALSE, 1),
			array('Patricie', FALSE, 1),
			array('Radomír', FALSE, 1),
			array('Prokop', FALSE, 1),
			array('Státní svátek - Cyril a Metoděj', TRUE, 2),
			array('Státní svátek - Mistr Jan Hus', TRUE, 1),
			array('Bohuslava', FALSE, 1),
			array('Nora', FALSE, 1),
			array('Drahoslava', FALSE, 1),
			array('Libuše a Amálie', FALSE, 2),
			array('Olga', FALSE, 1),
			array('Bořek', FALSE, 1),
			array('Markéta', FALSE, 1),
			array('Karolína', FALSE, 1),
			array('Jindřich', FALSE, 1),
			array('Luboš', FALSE, 1),
			array('Martina', FALSE, 1),
			array('Drahomíra', FALSE, 1),
			array('Čeněk', FALSE, 1),
			array('Ilja', FALSE, 1),
			array('Vítězslav', FALSE, 1),
			array('Magdaléna', FALSE, 1),
			array('Libor', FALSE, 1),
			array('Kristýna', FALSE, 1),
			array('Jakub', FALSE, 1),
			array('Anna', FALSE, 1),
			array('Věroslav', FALSE, 1),
			array('Viktor', FALSE, 1),
			array('Marta', FALSE, 1),
			array('Bořivoj', FALSE, 1),
			array('Ignác', FALSE, 1),
		),

		8 => array(
			1 => array('Oskar', FALSE, 1),
			array('Gustav', FALSE, 1),
			array('Miluše', FALSE, 1),
			array('Dominik', FALSE, 1),
			array('Kristian', FALSE, 1),
			array('Oldřiška', FALSE, 1),
			array('Lada', FALSE, 1),
			array('Soběslav', FALSE, 1),
			array('Roman', FALSE, 1),
			array('Vavřinec', FALSE, 1),
			array('Zuzana', FALSE, 1),
			array('Klára', FALSE, 1),
			array('Alena', FALSE, 1),
			array('Alan', FALSE, 1),
			array('Hana', FALSE, 1),
			array('Jáchym', FALSE, 1),
			array('Petra', FALSE, 1),
			array('Helena', FALSE, 1),
			array('Ludvík', FALSE, 1),
			array('Bernard', FALSE, 1),
			array('Johana', FALSE, 1),
			array('Bohuslav', FALSE, 1),
			array('Sandra', FALSE, 1),
			array('Bartoloměj', FALSE, 1),
			array('Radim', FALSE, 1),
			array('Luděk', FALSE, 1),
			array('Otakar', FALSE, 1),
			array('Augustýn', FALSE, 1),
			array('Evelína', FALSE, 1),
			array('Vladěna', FALSE, 1),
			array('Pavlína', FALSE, 1),
		),

		9 => array(
			1 => array('Linda a Samuel', FALSE, 2),
			array('Adéla', FALSE, 1),
			array('Bronislav', FALSE, 1),
			array('Jindřiška', FALSE, 1),
			array('Boris', FALSE, 1),
			array('Boleslav', FALSE, 1),
			array('Regína', FALSE, 1),
			array('Mariana', FALSE, 1),
			array('Daniela', FALSE, 1),
			array('Irma', FALSE, 1),
			array('Denisa', FALSE, 1),
			array('Marie', FALSE, 1),
			array('Lubor', FALSE, 1),
			array('Radka', FALSE, 1),
			array('Jolana', FALSE, 1),
			array('Ludmila', FALSE, 1),
			array('Naděžda', FALSE, 1),
			array('Kryštof', FALSE, 1),
			array('Zita', FALSE, 1),
			array('Oleg', FALSE, 1),
			array('Matouš', FALSE, 1),
			array('Darina', FALSE, 1),
			array('Berta', FALSE, 1),
			array('Jaromír', FALSE, 1),
			array('Zlata', FALSE, 1),
			array('Andrea', FALSE, 1),
			array('Jonáš', FALSE, 1),
			array('Václav', FALSE, 1),
			array('Michal', FALSE, 1),
			array('Jeroným', FALSE, 1),
		),

		10 => array(
			1 => array('Igor', FALSE, 1),
			array('Olivie a Oliver', FALSE, 2),
			array('Bohumil', FALSE, 1),
			array('František', FALSE, 1),
			array('Eliška', FALSE, 1),
			array('Hanuš', FALSE, 1),
			array('Justýna', FALSE, 1),
			array('Věra', FALSE, 1),
			array('Štefan a Sára', FALSE, 2),
			array('Marina', FALSE, 1),
			array('Andrej', FALSE, 1),
			array('Marcel', FALSE, 1),
			array('Renáta', FALSE, 1),
			array('Agáta', FALSE, 1),
			array('Tereza', FALSE, 1),
			array('Havel', FALSE, 1),
			array('Hedvika', FALSE, 1),
			array('Lukáš', FALSE, 1),
			array('Michaela', FALSE, 1),
			array('Vendelín', FALSE, 1),
			array('Brigita', FALSE, 1),
			array('Sabina', FALSE, 1),
			array('Teodor', FALSE, 1),
			array('Nina', FALSE, 1),
			array('Beáta', FALSE, 1),
			array('Erik', FALSE, 1),
			array('Šarlota a Zoe', FALSE, 2),
			array('Státní svátek', TRUE, 1),
			array('Silvie', FALSE, 1),
			array('Tadeáš', FALSE, 1),
			array('Štěpánka', FALSE, 1),
		),

		11 => array(
			1 => array('Felix', FALSE, 1),
			array('Památka zesnulých', TRUE, 1),
			array('Hubert', FALSE, 1),
			array('Karel', FALSE, 1),
			array('Miriam', FALSE, 1),
			array('Liběna', FALSE, 1),
			array('Saskie', FALSE, 1),
			array('Bohumír', FALSE, 1),
			array('Bohdan', FALSE, 1),
			array('Evžen', FALSE, 1),
			array('Martin', FALSE, 1),
			array('Benedikt', FALSE, 1),
			array('Tibor', FALSE, 1),
			array('Sáva', FALSE, 1),
			array('Leopold', FALSE, 1),
			array('Otmar', FALSE, 1),
			array('Mahulena', FALSE, 1),
			array('Romana', FALSE, 1),
			array('Alžběta', FALSE, 1),
			array('Nikola', FALSE, 1),
			array('Albert', FALSE, 1),
			array('Cecílie', FALSE, 1),
			array('Klement', FALSE, 1),
			array('Emílie', FALSE, 1),
			array('Kateřina', FALSE, 1),
			array('Artur', FALSE, 1),
			array('Xenie', FALSE, 1),
			array('René', FALSE, 1),
			array('Zina', FALSE, 1),
			array('Ondřej', FALSE, 1),
		),

		12 => array(
			1 => array('Iva', FALSE, 1),
			array('Blanka', FALSE, 1),
			array('Svatoslav', FALSE, 1),
			array('Barbora', FALSE, 1),
			array('Jitka', FALSE, 1),
			array('Mikuláš', FALSE, 1),
			array('Ambrož a Benjamín', FALSE, 2),
			array('Květoslava', FALSE, 1),
			array('Vratislav', FALSE, 1),
			array('Julie', FALSE, 1),
			array('Dana', FALSE, 1),
			array('Simona', FALSE, 1),
			array('Lucie', FALSE, 1),
			array('Lýdie', FALSE, 1),
			array('Radana a Radan', FALSE, 2),
			array('Albína', FALSE, 1),
			array('Daniel', FALSE, 1),
			array('Miloslav', FALSE, 1),
			array('Ester', FALSE, 1),
			array('Dagmar', FALSE, 1),
			array('Natálie', FALSE, 1),
			array('Šimon', FALSE, 1),
			array('Vlasta', FALSE, 1),
			array('Adam a Eva', FALSE, 2),
			array('Boží hod', TRUE, 1),
			array('Štěpán', FALSE, 1),
			array('Žaneta', FALSE, 1),
			array('Bohumila', FALSE, 1),
			array('Judita', FALSE, 1),
			array('David', FALSE, 1),
			array('Silvestr', FALSE, 1),
		),
	);


	/** @return void */
	function render()
	{
		$month = (int) date('n');
		$day = (int) date('j');

		if (!isset(static::$namedays[$month][$day])) {
			throw new Nette\InvalidStateException("Pro $day. $month není definován žádný svátek.");
		}

		$this->template->current = static::$namedays[$month][$day];
		$this->template->render();
	}

}
